lumen-oss/lux

.envrc, .github/workflows/nix-build.yml, .gitignore, flake.lock, flake.nix, nix/overlay.nix
The obligatory flakeification :smile:
=> build: add nix dev + build environment + ci builds

rocks-lib/src/rocks/dependency.rs, rocks-lib/src/rocks/platform.rs, rocks-lib/src/rocks/rockspec.rs
This is stacked on #5.
Since `mlua` uses `Deserialize` for parsing, we can simplify things by doing the same.
=> refactor(lib/rockspec): use `Deserialize` instances for parsing

Cargo.lock, rocks-lib/Cargo.toml, rocks-lib/src/rockspec/build.rs, rocks-lib/src/rockspec/mod.rs
Followed by #9 
In a follow-up PR, I will replace the `BuildType` enum with a `BuildBackendSpec` type that we will parse using an intermediate struct, similar to what I did with the source spec.
=> feat(lib/rockspec): parse build information

flake.lock, flake.nix, rocks-bin/src/search.rs, rocks-lib/src/manifest/pull_manifest.rs, rocks-lib/src/rockspec/build/mod.rs, rocks-lib/src/rockspec/mod.rs
Stacked on #14.
This enables clippy and cargo check in CI.
For now, I've switched to my fork of pre-commit-hooks.nix, pending: https://github.com/cachix/pre-commit-hooks.nix/pull/396.
=> ci: enable clippy and cargo check

Cargo.lock, rocks-bin/Cargo.toml, rocks-bin/src/main.rs, rocks-bin/src/rockspec/github_metadata.rs, rocks-bin/src/rockspec/mod.rs, rocks-bin/src/rockspec/write_rockspec.rs, rocks-lib/src/rockspec/dependency.rs
This PR adds luarocks's `write-rockspec` command with quite a few tweaks.
This PR adds npm/yarn-like prompts for building up a rockspec file for a given project. It pulls any metadata it might need from either github or the local git repo to provide sane defaults :)
=> [FEATURE]: Add `write-rockspec` command

rocks-bin/src/search.rs
This PR extends (and is based) on the changes made in #26. Running `rocks search --porcelain` will now also produce JSON output.
=> refactor!: produce JSON output when --porcelain is provided in `rocks search`

rocks-lib/src/lib.rs, rocks-lib/src/luarock/mod.rs, rocks-lib/src/luarock/version.rs, rocks-lib/src/rockspec/dependency.rs, rocks-lib/src/rockspec/mod.rs
This PR attempts to refactor the components of `rockspec/dependency.rs`.
Question: does `LuaDependency` also theoretically counts as a "luarock", but I've decided to keep that in the old `dependency.rs` file, which I feel makes sense. Feedback is welcome on this.
=> refactor: move Luarock class into separate file

Cargo.lock, rocks-lib/Cargo.toml, rocks-lib/src/rockspec/platform.rs
This PR fixes clippy's complaints about invalid target OS checks. As it turns out, checking for cygwin is not a simple task, but is there any reason that we should check for cygwin explicitly?
=> fix: make clippy happy

rocks-lib/src/luarock/version.rs, rocks-lib/src/rockspec/dependency.rs
fixes #37. This allows the deserialization of `rock == version` in rockspecs.
=> fix: allow `rock == version` parsing in rockspecs

.github/workflows/nix-release-build.yml, .gitignore, Cargo.lock, flake.lock, flake.nix, nix/overlay.nix, rocks-bin/Cargo.toml, rocks-lib/Cargo.toml
Closes #53 
Nix by default builds rust packages with the `release` profile.
We don't need this for running tests on PR.
This PR introduces the following changes:
- Build with the `release` profile on push to `master`.
- Run checks (including checks) with the `debug` profile on PR.
- Add builds on darwin.
- Add `libgit2` to the `buildInputs` (required on darwin).
=> ci: don't run release build on PR + run on mac

rocks-bin/src/project/write_new.rs, rocks-lib/Cargo.toml, rocks-lib/src/lua_package/mod.rs, rocks-lib/src/lua_package/version.rs
Stacked on #55.
Closes #48.
This adds wrapper types around `semver::Version` and `semver::VersionReq` that add support for luarocks `dev` versions.
=> feat: support luarocks dev versions

.gitignore, rocks-bin/src/build.rs, rocks-bin/src/download.rs, rocks-bin/src/install.rs, rocks-bin/src/install_lua.rs, rocks-bin/src/list.rs, rocks-bin/src/main.rs, rocks-bin/src/outdated.rs, rocks-bin/src/project/write_new.rs, rocks-bin/src/search.rs, rocks-bin/src/unpack.rs, rocks-lib/src/build/builtin.rs, rocks-lib/src/build/mod.rs, rocks-lib/src/config/mod.rs, rocks-lib/src/lua_installation/mod.rs, rocks-lib/src/manifest/metadata.rs, rocks-lib/src/manifest/pull_manifest.rs, rocks-lib/src/operations/download.rs, rocks-lib/src/project/mod.rs, rocks-lib/src/rockspec/mod.rs, rocks-lib/src/tree/list.rs, rocks-lib/src/tree/mod.rs
This is a draft implementation of project-local rock trees. If `rocks` detects it's in a project, it will always interact with the project-local rock tree first. Pass `--no-project` to prevent these interactions.
=> feat: project-local rocktrees

rocks-bin/src/main.rs, rocks-lib/src/lua_package/outdated.rs
stacked on #67. the command is no longer necessary.
=> fix: remove unused `rocks init`

rocks-lib/src/lua_package/mod.rs, rocks-lib/src/manifest/metadata.rs
This PR was supposed to be much longer, but I decided that we were layering on too much complexity with no benefit whatsoever.
This PR fixes #79 in two ways: firstly, it fixes the broken version checking code (and now defaults to the latest version correctly). Secondly, it permits rock names to now also have .s in their names.
Instead of trying to create a generic catch-all parser, I think restricting rocks to this format is both sane and expected. During the big error rewrite, we can issue nice error messages to the user so they're never confused.
=> fix: version and rock name parsing errors (#79)

.github/workflows/nix-build.yml
This action uses GitHub's local cache, which gives us faster builds, but we can't fetch them locally.  I think this is a better choice for PR builds.
=> ci: use magic-nix-cache-action for non release builds

.github/workflows/nix-release-build.yml
With #84, we need to build the devShells here to have them available on cachix.
=> ci: build devShells on release build

.cargo/config.toml, .github/workflows/integration-tests.yml, CONTRIBUTING.md, nix/overlay.nix, rocks-lib/Cargo.toml, rocks-lib/src/build/builtin.rs, rocks-lib/src/tree/mod.rs, rocks-lib/src/tree/snapshots/rocks_lib__tree__tests__tree_list.snap, rocks-lib/tests/build.rs
This PR splits out the integration tests and adds a GH action for running them.
We only run the `--lib` tests in the Nix build.
=> tests: separate integration tests

Cargo.lock, rocks-lib/Cargo.toml, rocks-lib/src/build/fetch.rs, rocks-lib/src/build/mod.rs, rocks-lib/src/rockspec/mod.rs, rocks-lib/src/rockspec/rock_source.rs
This adds support for rockspecs with `.zip` or `.tar`/`.tar.gz` archives in their source URLs.
I've tested it manually with haskell-tools.nvim (which has a zip archive in the `source.url`).
=> feat(install): implement rockspec URLs

rocks-lib/Cargo.toml
The `cc` crate has a `parallel` feature that enables parallel compilation.
=> feat(build): enable parallel compilation

rocks-lib/src/lua_package/version.rs, rocks-lib/src/rockspec/mod.rs, rocks-lib/src/tree/mod.rs, rocks-lib/src/tree/snapshots/rocks_lib__tree__tests__tree_list.snap
specrev is likely to lead to all sorts of issues.
Let's not support it (at least for now).
=> fix(version): trim specrev when parsing

rocks-bin/src/build.rs, rocks-lib/src/build/builtin.rs, rocks-lib/src/build/make.rs, rocks-lib/src/build/mod.rs, rocks-lib/src/operations/install.rs, rocks-lib/src/rockspec/build/mod.rs
We might end up removing them again when we parallelise our builds, but for now they might improve the UI for larger builds.
Stacked on #129
=> feat(ui): add some progress bars

rocks-bin/src/info.rs, rocks-bin/src/main.rs
This feature is so uninspiring that I stopped working on it halfway, thus it's a draft :smile: 
I'd like to first implement `rocks doc` and have a general interface for grabbing documentation, so that it can be showed to the user when invoking `rocks info`.
I renamed `rocks show` to `rocks info` because `show` has always felt incredibly unintuitive to me. We may even want to make `rocks info` work for any rock, both remote and local, and display whether it's installed or not in the output.
=> feat: add `rocks info` command

rocks-bin/src/format.rs, rocks-lib/src/config/mod.rs, rocks-lib/src/manifest/pull_manifest.rs
This opens the door for customizable cache directories from the CLI, but is also important to (finally) properly isolate the manifest tests.
=> refactor(config)!: allow customizable cache and data directories

rocks-lib/src/operations/fetch.rs, rocks-lib/src/rockspec/mod.rs, rocks-lib/src/rockspec/rock_source.rs
This PR fixes the installations of `dkjson`, which doesn't specify a `dir` name, even though it theoretically should.
This is fixed by implementing luarocks's "smart" search in tar files, which just involves checking if the unpacked contents of the tar is a single directory and recursively unpacking the directory instead.
=> fix: properly unpack tar archives

rocks-lib/src/build/builtin.rs, rocks-lib/src/rockspec/build/utils/mod.rs
Addresses #182.
However, this doesn't fully solve the issue, because:
- https://github.com/rust-lang/cc-rs/issues/594
- #188.
=> fix: install `src/<lib>.c` modules correctly

rocks-lib/src/build/builtin.rs, rocks-lib/src/build/mod.rs, rocks-lib/src/rockspec/build/builtin.rs, rocks-lib/src/rockspec/build/mod.rs, rocks-lib/src/rockspec/build/utils/mod.rs, rocks-lib/src/rockspec/mod.rs
=> fix(build/builtin): platform overrides + modules compilation

Cargo.lock, Cargo.toml, rocks-lib/Cargo.toml, rocks-lib/src/lockfile/mod.rs, rocks-lib/src/package/mod.rs, rocks-lib/src/tree/mod.rs, rocks-lib/tests/tree.rs
What it says on the tin: this PR adds a `lua` feature flag and implements UserData for all major data types in the codebase. This will be complemented by a second PR that adds a `rocks-lua` module, allowing `rocks` to be packaged and used directly in any Lua application.
Notes: we could implement __tostring methods for all these types later down the road, making debugging them easier. What do we think?
=> feat: implement UserData for all major structs

rocks-bin/src/list.rs
Fixes a slight annoyance where the package name would be displayed multiple times in `rocks list` output.
=> fix(list): show package name only once

rocks-lib/src/operations/install.rs, rocks-lib/src/rockspec/build/mod.rs, rocks-lib/src/rockspec/mod.rs, rocks-lib/src/rockspec/platform.rs, rocks-lib/src/rockspec/rock_source.rs, rocks-lib/src/rockspec/test_spec.rs
This PR accumulates the IDs of rocks during the initial dependency search, creating a dependency graph as it chugs along. After installing the required packages, this dependency graph is referenced to properly build up the lockfile.
To test this, first `rocks purge` your tree, which will also remove the `lock.json`. Then, install your favourite package and `cat /my/tree/5.4/lock.json` :)
=> fix(install): properly assign dependencies in the lockfile

rocks-bin/src/build.rs, rocks-bin/src/download.rs, rocks-bin/src/fetch.rs, rocks-bin/src/info.rs, rocks-bin/src/install.rs, rocks-bin/src/remove.rs, rocks-bin/src/test.rs, rocks-bin/src/unpack.rs, rocks-bin/src/update.rs, rocks-lib/src/build/builtin.rs, rocks-lib/src/build/make.rs, rocks-lib/src/build/mod.rs, rocks-lib/src/build/rust_mlua.rs, rocks-lib/src/operations/download.rs, rocks-lib/src/operations/fetch.rs, rocks-lib/src/operations/install.rs, rocks-lib/src/operations/remove.rs, rocks-lib/src/operations/run.rs, rocks-lib/src/operations/test.rs, rocks-lib/src/operations/unpack.rs, rocks-lib/src/operations/update.rs, rocks-lib/src/progress.rs, rocks-lib/src/rockspec/build/mod.rs, rocks-lib/tests/build.rs, rocks-lib/tests/test.rs
This refactors the entire library to allow progress indicators to be optional (crucial for #201).
This introduces a sealed trait called `HasProgress` and an enum called `Progress`. These allow the usage of either `MultiProgress` or `ProgressBar` in a similar fashion to how you would use an `Option<T>`.
Note: this PR doesn't implement a `--silent` flag of any kind, and continues to assume that `Progress` should always be displayed through the CLI. This PR serves as the skeleton for that feature, which may be implemented in a separate PR.
Let me know what you think @mrcjkb.
=> refactor!: make progress indicators optional

Cargo.lock, rocks-lib/Cargo.toml, rocks-lib/resources/test/sample-project-no-build-spec/lua/foo/bar/baz.lua, rocks-lib/resources/test/sample-project-no-build-spec/lua/foo/bar/init.lua, rocks-lib/resources/test/sample-project-no-build-spec/lua/foo/init.lua, rocks-lib/resources/test/sample-project-no-build-spec/project.rockspec, rocks-lib/src/build/builtin.rs, rocks-lib/src/build/mod.rs, rocks-lib/src/build/rust_mlua.rs, rocks-lib/src/build/utils.rs, rocks-lib/src/path.rs, rocks-lib/src/rockspec/build/builtin.rs, rocks-lib/src/rockspec/build/mod.rs
=> fix(build/builtin): properly auto-detect modules

rocks-bin/src/build.rs, rocks-bin/src/install.rs, rocks-bin/src/test.rs, rocks-bin/src/update.rs, rocks-lib/src/luarocks_installation.rs, rocks-lib/src/operations/install.rs, rocks-lib/src/operations/resolve.rs, rocks-lib/src/operations/run.rs, rocks-lib/src/operations/test.rs, rocks-lib/src/operations/update.rs, rocks-lib/src/progress.rs, rocks-lib/tests/test.rs
I think cloning a `MultiProgress` could be leading to strange behaviour.
This should fix it.
=> fix: duplicated progress bars

flake.nix, nix/overlay.nix, rocks-lib/src/build/external_dependency.rs, rocks-lib/src/build/mod.rs, rocks-lib/src/config/external_deps.rs, rocks-lib/src/config/mod.rs, rocks-lib/src/rockspec/dependency.rs, rocks-lib/src/rockspec/mod.rs
Stacked on #267 
Closes #174.
- Uses pkg-config and then falls back to a built-in mechanism based on the LuaRocks implementation.
=> feat(build): fail if `external_dependencies` can't be found

rocks-lib/src/lockfile/mod.rs, rocks-lib/src/luarocks_installation.rs, rocks-lib/src/operations/install.rs, rocks-lib/src/operations/resolve.rs, rocks-lib/src/tree/list.rs, rocks-lib/src/tree/mod.rs
- In `resolve::get_all_dependencies`, we filter out dependencies that are already installed, as long as the `build_behaviour` is `NoForce`.
- We set the build behaviour to `NoForce` for dependencies.
This means that we don't reinstall dependencies when reinstalling a rock. (Is this desirable behaviour? :thinking:).
=> feat: don't reinstall dependencies that are already installed

rocks-bin/src/path.rs, rocks-bin/src/run.rs, rocks-bin/src/run_lua.rs, rocks-lib/src/luarocks_installation.rs, rocks-lib/src/operations/run.rs, rocks-lib/src/operations/test.rs, rocks-lib/src/path.rs
Closes #281.
Also changes the `--append` flag for the `rocks path` command to `--prepend`.
=> fix!: prepend paths instead of appending them

rocks-bin/src/build.rs, rocks-bin/src/download.rs, rocks-bin/src/fetch.rs, rocks-bin/src/info.rs, rocks-bin/src/install.rs, rocks-bin/src/main.rs, rocks-bin/src/outdated.rs, rocks-bin/src/remove.rs, rocks-bin/src/search.rs, rocks-bin/src/test.rs, rocks-bin/src/unpack.rs, rocks-bin/src/update.rs, rocks-lib/src/config/mod.rs, rocks-lib/src/lib.rs, rocks-lib/src/luarocks_installation.rs, rocks-lib/src/manifest/mod.rs, rocks-lib/src/operations/download.rs, rocks-lib/src/operations/install.rs, rocks-lib/src/operations/resolve.rs, rocks-lib/src/operations/run.rs, rocks-lib/src/operations/test.rs, rocks-lib/src/operations/update.rs, rocks-lib/src/package/outdated.rs, rocks-lib/src/remote_package_db/mod.rs, rocks-lib/tests/test.rs
In preparation for #159.
This PR makes the `Manifest` and `ManifestMetadata` types `pub(crate)`. `rocks-lib` now only exposes the `RemotePackageDB` type (which could one day be a client to a non-luarocks server).
=> feat!: support installing from multiple servers

rocks-bin/src/check.rs, rocks-bin/src/lib.rs, rocks-bin/src/main.rs, rocks-lib/src/project/mod.rs
Adds a simple implementation of `rocks check`, which ensures `luacheck` is installed and runs it for the whole source directory of a given project.
Similarly to `rocks fmt`, we'll want to expand this to take in a path as an argument for finer control.
I don't believe we should let the user control `luacheck` with flags, that should be up to the luacheckrc file.
=> feat: `rocks check`

rocks-lib/resources/test/sample-project-lockfile-missing-deps/project.rockspec, rocks-lib/resources/test/sample-project-lockfile-missing-deps/rocks.lock, rocks-lib/src/build/mod.rs, rocks-lib/src/manifest/mod.rs, rocks-lib/src/operations/fetch.rs, rocks-lib/src/operations/lockfile_update.rs
=> fix(lockfile): compute integrity of packed source

rocks-bin/src/fetch.rs, rocks-lib/src/build/mod.rs, rocks-lib/src/operations/fetch.rs
=> feat!(fetch): fall back to fetching `.src.rock`

rocks-bin/src/install_rockspec.rs, rocks-bin/src/lib.rs, rocks-bin/src/main.rs, rocks-lib/resources/test/sample-project-lockfile-missing-deps/README.md, rocks-lib/resources/test/sample-project-lockfile-missing-deps/lua/foo.lua, rocks-lib/resources/test/sample-project-lockfile-missing-deps/project.rockspec, rocks-lib/resources/test/sample-project-lockfile-missing-deps/rocks.lock, rocks-lib/src/build/mod.rs, rocks-lib/src/lockfile/mod.rs, rocks-lib/src/manifest/mod.rs, rocks-lib/src/operations/download.rs, rocks-lib/src/operations/fetch.rs, rocks-lib/src/operations/install.rs, rocks-lib/src/operations/lockfile_update.rs, rocks-lib/src/operations/mod.rs, rocks-lib/src/operations/pin.rs, rocks-lib/src/operations/remove.rs, rocks-lib/src/operations/resolve.rs, rocks-lib/src/package/mod.rs, rocks-lib/src/package/outdated.rs, rocks-lib/src/project/mod.rs, rocks-lib/src/remote_package_db/mod.rs, rocks-lib/src/rockspec/platform.rs, rocks-lib/src/tree/mod.rs, rocks-lib/tests/build.rs
This PR:
- Introduces a `RocksPackageDB` implementation using a lockfile.
- Uses that implementation to provide reproducible project builds, with rockspec/source integrity checks.
Breaking:
- `rocks build` it now builds the current project,
using a clone of the rockspec with the project root as the source.
This is now equivalent to `luarocks make` or `cargo build`.
- Introduced a separate `install-rockspec` command for installing local rockspecs.
- Removed the `--force` flag, because if we're building from a project or local rockspec, we probably always want to force.
=> feat!(rocks-bin/build): project lockfiles

.gitignore, Cargo.lock, rocks-lib/Cargo.toml, rocks-lib/resources/test/sample-project-lockfile-missing-deps/rocks.lock, rocks-lib/resources/test/sample-tree/5.1/lock.json, rocks-lib/src/build/builtin.rs, rocks-lib/src/build/cmake.rs, rocks-lib/src/build/command.rs, rocks-lib/src/build/luarocks.rs, rocks-lib/src/build/make.rs, rocks-lib/src/build/mod.rs, rocks-lib/src/build/rust_mlua.rs, rocks-lib/src/lockfile/mod.rs, rocks-lib/src/lockfile/snapshots/rocks_lib__lockfile__tests__add_rocks.snap, rocks-lib/src/lockfile/snapshots/rocks_lib__lockfile__tests__parse_lockfile.snap, rocks-lib/src/luarocks/install_binary_rock.rs, rocks-lib/src/operations/lockfile_update.rs, rocks-lib/src/operations/remove.rs, rocks-lib/src/operations/resolve.rs, rocks-lib/src/rockspec/build/mod.rs, rocks-lib/src/rockspec/mod.rs, rocks-lib/src/tree/mod.rs
This PR keeps track of all binaries installed by a given rock and properly cleans up the binaries when running `rocks remove`.
I also made sure to sanitize the path input before reading its filename just in case to prevent any sort of DOS. Whether it's as effective as I hope should be looked into as part of a security check.
=> fix!: remove associated binaries when deleting a rock

rocks-bin/src/build.rs, rocks-bin/src/outdated.rs, rocks-bin/src/search.rs, rocks-lib/src/luarocks/luarocks_installation.rs, rocks-lib/src/manifest/mod.rs, rocks-lib/src/operations/download.rs, rocks-lib/src/operations/install.rs, rocks-lib/src/operations/lockfile_update.rs, rocks-lib/src/operations/update.rs, rocks-lib/src/remote_package_db/mod.rs
...at least this will prevent people from thinking rocks is dead if downloading the manifest on a slow connection.
=> feat(ui): show spinner while downloading manifest

Cargo.lock, rocks-bin/Cargo.toml, rocks-bin/src/config.rs, rocks-bin/src/doc.rs, rocks-bin/src/lib.rs, rocks-bin/src/main.rs, rocks-lib/src/config/mod.rs
Stacked on #353.
Closes #95. I don't think we need to replicate the `luarocks config <path.to.config> <value>` CLI.
A toml file should be good enough, as long as we document it.
=> feat: rocks config command

Cargo.lock, rocks-bin/Cargo.toml, rocks-bin/src/config.rs, rocks-bin/src/doc.rs, rocks-bin/src/lib.rs, rocks-bin/src/main.rs, rocks-bin/src/run_lua.rs, rocks-lib/Cargo.toml, rocks-lib/src/build/external_dependency.rs, rocks-lib/src/build/mod.rs, rocks-lib/src/config/external_deps.rs, rocks-lib/src/config/mod.rs, rocks-lib/src/luarocks/install_binary_rock.rs, rocks-lib/src/manifest/mod.rs, rocks-lib/tests/build.rs, rocks-lib/tests/luarocks_installation.rs, rocks-lib/tests/run.rs, rocks-lib/tests/test.rs
- Implements `Deserialize` for `ConfigBuilder`.
- `ConfigBuilder::new()` now deserializes from a `config.toml` file if present.
=> feat(config): config.toml

README.md, rocks-lib/src/config/mod.rs, rocks-lib/src/manifest/mod.rs
This is now a PR for namespaces because of a jj split.
Closes #372
=> feat: manifest namespaces

rocks-bin/src/project/new.rs, rocks-lib/src/lockfile/mod.rs, rocks-lib/src/luarocks/luarocks_installation.rs, rocks-lib/src/manifest/mod.rs, rocks-lib/src/operations/resolve.rs, rocks-lib/src/package/mod.rs, rocks-lib/src/package/outdated.rs, rocks-lib/src/package/version.rs, rocks-lib/src/project/mod.rs, rocks-lib/src/project/rocks_toml.rs, rocks-lib/src/remote_package_db/mod.rs, rocks-lib/src/rockspec/mod.rs, rocks-lib/src/tree/mod.rs
Stacked on #369.
Closes #364.
This also changes the behaviour when installing with a `--dev` flag.
`foo >= <semver>` without an upper constraint no longer matches `<dev>`.
Only `Any` and `<dev>` can match `<dev>`, which I think will result in less surprises for users.
For example, `rocks --dev update` won't update semver packages to dev versions.
=> chore: Add `PackageVersionReq::Any` variant

rocks-bin/src/add.rs, rocks-bin/src/build.rs, rocks-bin/src/check.rs, rocks-bin/src/doc.rs, rocks-bin/src/info.rs, rocks-bin/src/install.rs, rocks-bin/src/install_rockspec.rs, rocks-bin/src/list.rs, rocks-bin/src/outdated.rs, rocks-bin/src/pack.rs, rocks-bin/src/path.rs, rocks-bin/src/pin.rs, rocks-bin/src/purge.rs, rocks-bin/src/remove.rs, rocks-bin/src/run.rs, rocks-bin/src/run_lua.rs, rocks-bin/src/uninstall.rs, rocks-bin/src/update.rs, rocks-lib/src/build/mod.rs, rocks-lib/src/config/mod.rs, rocks-lib/src/luarocks/install_binary_rock.rs, rocks-lib/src/luarocks/luarocks_installation.rs, rocks-lib/src/operations/install.rs, rocks-lib/src/operations/remove.rs, rocks-lib/src/operations/run.rs, rocks-lib/src/operations/test.rs, rocks-lib/src/operations/update.rs, rocks-lib/src/project/mod.rs, rocks-lib/src/which/mod.rs, rocks-lib/tests/build.rs
Simplifies the handling of Lua versions and tree configurations. This prevents stupid mistakes from happening where you try to operate on the user-wide tree but instead operate on the local project's tree because the default config would automatically assign the tree to the current project.
Each commit is a specific distinct aspect of this rewrite, but the first three commits do not produce a buildable rust project. I guess we'll want to squash + merge this after review.
=> refactor!: improve API to prevent logic errors with Project lockfiles

rocks-lib/src/build/mod.rs, rocks-lib/src/operations/fetch.rs, rocks-lib/src/operations/unpack.rs
Scenario:
An older rockspec that does not specify a `source.dir` and for which the `source.url` no longer exists:
```lua
source = {
url = "http://www.kyne.com.au/~mark/software/download/lua-cjson-2.1.0.zip",
}
```
The luarocks `src.rock` looks like this:
- `lua-cjson-2.1.0-1.src.rock`
- `lua-cjson-2.1.0-1.rockspec`
-  `lua-cjson-2.1.0.zip` -> contains the directory: `lua-cjson-2.1.0` (not specified in the `source.dir`).
To account for this, we need to recursively unpack the nested source archive and infer the source directory.
=> fix: recursively unpack nested archives

rocks-lib/resources/test/sample-tree/5.1/lock.json, rocks-lib/src/lockfile/mod.rs
Since the lockfile is checked into vcs, it's better to retain ordering of the dependencies and entrypoints, to minimise diff sizes.
Stacked on #403 (to avoid merge conflicts)
=> fix(lockfile): Retain ordering of entries

lux-lib/src/build/mod.rs, lux-lib/src/lockfile/mod.rs, lux-lib/src/manifest/mod.rs, lux-lib/src/operations/download.rs, lux-lib/src/operations/fetch.rs, lux-lib/src/operations/install.rs, lux-lib/src/package/mod.rs, lux-lib/src/remote_package_db/mod.rs
Stacked on #422.
Closes #424.
With this PR, we use the lockfile's `source_url` as a source of truth for downloading the rock source.
That way, we're less likely to run into source integrity mismatches if no git revision or tag is specified in the rockspec source.
=> feat: use lockfile source when fetching a package

lux-lib/resources/test/lux.lock, lux-lib/src/lockfile/mod.rs
This will make the lockfile a bit nicer when used with rocks.nvim, where we don't care about build/test dependencies.
=> feat(lockfile): don't serialise dependencies fields if empty

lux-cli/src/bin/lx.rs, lux-cli/src/sync.rs, lux-cli/src/update.rs, lux-lib/src/lockfile/mod.rs, lux-lib/src/operations/sync.rs, lux-lib/src/operations/test.rs, lux-lib/src/operations/update.rs
Stacked on #425.
Addresses #426 (partially).
Also fixes `Sync` so that it keeps only packages that have the same constraints as the `Vec<PackageReq>` constraints we pass in from the lux.toml dependencies.
This ensures that if we update a version constraint in `lux.toml`, it is reflected in the lockfile.
=> feat(update): operate on lux.toml and lux.lock if in a project

.cargo/config.toml, .github/workflows/nix-build.yml, Cargo.toml, flake.nix, lux-lib/Cargo.toml, nix/overlay.nix
- Use crane instead of git-hooks.nix for clippy checks, so we can reuse the cached dependencies.
- Add taplo to the git-hooks checks (for toml formatting).
Closes #447
=> build: use crane for clippy and rustfmt checks

Cargo.lock, README.md, lux-lib/Cargo.toml, lux-lib/resources/test/tree-sitter-rust-0.0.43.rockspec, lux-lib/src/build/mod.rs, lux-lib/src/build/treesitter_parser.rs, lux-lib/src/lua_rockspec/build/mod.rs, lux-lib/src/lua_rockspec/build/tree_sitter.rs, lux-lib/tests/build.rs
With this, `lux` users won't need to install tree-sitter-cli separately to build tree-sitter parsers.
=> feat(build): treesitter-parser build backend

lux-cli/src/build.rs, lux-cli/src/check.rs, lux-cli/src/install.rs, lux-cli/src/install_rockspec.rs, lux-cli/src/pack.rs, lux-cli/src/utils/install.rs, lux-lib/resources/test/lux.lock, lux-lib/resources/test/sample-tree/5.1/lux.lock, lux-lib/src/build/mod.rs, lux-lib/src/lockfile/mod.rs, lux-lib/src/lockfile/snapshots/lux_lib__lockfile__tests__add_rocks.snap, lux-lib/src/lockfile/snapshots/lux_lib__lockfile__tests__parse_lockfile.snap, lux-lib/src/luarocks/install_binary_rock.rs, lux-lib/src/luarocks/luarocks_installation.rs, lux-lib/src/operations/install.rs, lux-lib/src/operations/install_spec.rs, lux-lib/src/operations/mod.rs, lux-lib/src/operations/resolve.rs, lux-lib/src/operations/run.rs, lux-lib/src/operations/sync.rs, lux-lib/src/operations/test.rs, lux-lib/src/operations/update.rs
Stacked on #436 (to avoid conflicting with it).
This PR introduces the following new concepts:
- `lockfile::OptState`, which can be `Required` and `Optional`.
For now, this doesn't have much meaning to lux, but it influences the `LocalPackageId` hash
and will be useful later.
- `PackageInstallSpec`, which replaces the `(BuildBehaviour, PackageReq)` tuple
and includes the `PinnedState` and `OptState`.
The reason for this is so that when building a local project, we can support stuff like this:
```toml
[dependencies.foo]
version = "1.0.0"
opt = true
pin = true
```
This will require a follow-up PR that introduces a `Dependency` type with an `into_package_req` method.
The `*ProjectToml` types will then have lists of `Vec<Dependency>` instead of `Vec<PackageReq>`.
The reason for introducing …
=> feat!: optional packages

.vscode/settings.json, Cargo.lock, lux-cli/src/add.rs, lux-cli/src/build.rs, lux-cli/src/install_rockspec.rs, lux-cli/src/remove.rs, lux-cli/src/update.rs, lux-lib/src/lua_rockspec/mod.rs, lux-lib/src/lua_rockspec/partial.rs, lux-lib/src/lua_rockspec/platform.rs, lux-lib/src/luarocks/luarocks_installation.rs, lux-lib/src/operations/install.rs, lux-lib/src/operations/resolve.rs, lux-lib/src/operations/test.rs, lux-lib/src/operations/update.rs, lux-lib/src/package/mod.rs, lux-lib/src/project/mod.rs, lux-lib/src/project/project_toml.rs, lux-lib/src/rockspec/lua_dependency.rs, lux-lib/src/rockspec/mod.rs, lux-lua/Cargo.toml, nix/overlay.nix
Stacked on #453.
This doesn't change any behaviour yet. It's just in preparation for supporting things like
```toml
[dependencies.foo]
version = "1.0.0"
opt = true
pin = true
```
This PR introduces a `LuaDependency` type, which is equivalent to `PackageReq`, but will be able to hold more info in the future, which may be useful for building local projects.
=> refactor!: extract `LuaDependency` type

.vscode/settings.json, lux-cli/src/add.rs, lux-cli/src/build.rs, lux-cli/src/check.rs, lux-cli/src/remove.rs, lux-lib/src/lockfile/mod.rs, lux-lib/src/luarocks/luarocks_installation.rs, lux-lib/src/operations/install_spec.rs, lux-lib/src/operations/run.rs, lux-lib/src/operations/sync.rs, lux-lib/src/operations/test.rs, lux-lib/src/operations/update.rs, lux-lib/src/project/mod.rs, lux-lib/src/project/project_toml.rs, lux-lib/src/rockspec/lua_dependency.rs
Stacked on #454.
This adds the ability to set the `opt` and `pin` fields for a Lua dependency via the `lux.toml` entries.
=> feat!(toml): `opt` and `pin` fields

lux-cli/src/project/new.rs, lux-lib/src/project/mod.rs
Used to prevent unnecessary warnings when creating a project within a subdirectory of an existing project.
=> fix(`lx new`): don't search parents for existing project

lux-cli/src/project/new.rs
This activates the `hjkl` keys and makes the experience easier when selecting from a dropdown in the terminal.
=> feat: enable vim mode for `lx new` selections

lux-cli/src/exec.rs, lux-cli/src/path.rs, lux-cli/src/run_lua.rs, lux-lib/src/luarocks/luarocks_installation.rs, lux-lib/src/operations/exec.rs, lux-lib/src/operations/run.rs, lux-lib/src/operations/run_lua.rs, lux-lib/src/operations/test.rs, lux-lib/src/path.rs
closes #510 and improves user experience by no longer requiring them to `eval $(lx path ...)` all the time.
=> feat: implicitly propagate environment variables to subprocesses

lux-lua/Cargo.toml
that crate should only be built manually through xtask
=> fix: don't publish `lux-lua`

lux-cli/src/lib.rs
The previous description made it sound like Lux supports Lua debuggers.
=> chore: make `lx debug`'s description more obvious

Cargo.lock, lux-cli/Cargo.toml, lux-cli/src/bin/lx.rs, lux-cli/src/debug.rs, lux-cli/src/project/debug.rs, lux-cli/src/utils/file_tree.rs, lux-cli/src/utils/mod.rs, lux-lib/src/build/utils.rs, lux-lib/src/project/mod.rs
Can be run with
```
❯ : lx debug project --list-files
Project name: lux-t2
Project version: 0.1.0-1
Project location: /tmp/lux-t2
Included project files:
lux-t2
├── lux.lock
├── lux.toml
└── src
├── main.lua
└── repl.lua
.
```
=> feat(debug project): flag to list included files

release-plz.toml
This should finally fix `cargo binstall` not working with `lux-cli` :)
=> fix(release-plz): use a simpler release name for `lux-cli`

lux-lib/src/project/project_toml.rs
=> fix: `[run]` field overwritten by `extra.rockspec`

release-plz.toml
I hope this will fix our release bodies being empty.
=> fix(release-plz): don't use relative path for changelog

.github/workflows/release-plz.yml
I believe the PAT *should* have sufficient privileges :p
=> ci: use PAT for release-plz to allow subsequent workflow triggers

lux-lib/src/luarocks/rock_manifest.rs
Introduced in #579 (we don't run this test in CI - which is bad).
=> fix(pack): regression in manifest creation

lux-lib/src/build/treesitter_parser.rs, lux-lib/tests/build.rs
I can't test directly through the devshell since I'm in a region with poor internet currently, but a quick run of `parallel` with 4 separate treesitter installations has stopped throwing an error, so I assume this has fixed the problem. Further testing will be necessary.
=> fix(build/tree-sitter): race condition when building many parsers simultaneously

lux-cli/src/bin/lx.rs, lux-cli/src/generate_rockspec.rs, lux-cli/src/lib.rs
This can come in handy for people who'd like to create a rockspec for interoperability purposes - Lux will also name the rockspec in accordance with how `luarocks` expects it.
=> feat: `lx generate-rockspec`

Cargo.lock, lux-cli/resources/test/sample-project-init/lux.toml, lux-lib/resources/test/luaossl-20220711-0.rockspec, lux-lib/src/build/external_dependency.rs, lux-lib/src/lua_rockspec/dependency.rs, lux-lib/src/lua_rockspec/mod.rs, lux-lib/src/project/mod.rs, lux-workspace-hack/Cargo.toml
Fixes #631.
Some rockspecs have both `header` and `library` fields in their `external_dependencies` table.
Lux only allowed one of them.
=> fix: conflicting external dependency spec parse error

lux-cli/src/build.rs
`--ignore-lockfile` isn't a valid argument.
I noticed this in #631.
=> fix(cli): suggest `--no-lock` instead of `--ignore-lockfile`

lux-lib/src/package/version.rs
=> fix: parse versions without a contraint prefix as `=`

lux-lib/src/package/version.rs
This is in preparation for #329.
It will allow us to encode things like git commit hashes and arbitrary tags as `DevVer` versions.
=> feat(lux-lib): more lenient dev version parsing

lux-cli/src/build.rs, lux-cli/src/install_rockspec.rs, lux-lib/resources/test/sample-project-git-dependency/.gitignore, lux-lib/resources/test/sample-project-git-dependency/lux.toml, lux-lib/src/build/mod.rs, lux-lib/src/git/mod.rs, lux-lib/src/git/shorthand.rs, lux-lib/src/lib.rs, lux-lib/src/lockfile/mod.rs, lux-lib/src/lua_rockspec/mod.rs, lux-lib/src/lua_rockspec/rock_source.rs, lux-lib/src/operations/download.rs, lux-lib/src/operations/fetch.rs, lux-lib/src/operations/install.rs, lux-lib/src/operations/install_spec.rs, lux-lib/src/operations/resolve.rs, lux-lib/src/operations/sync.rs, lux-lib/src/operations/test.rs, lux-lib/src/operations/update.rs, lux-lib/src/project/mod.rs, lux-lib/src/project/project_toml.rs, lux-lib/src/rockspec/lua_dependency.rs, lux-lib/src/upload/mod.rs, lux-lib/tests/build.rs, lux-lib/tests/install.rs
This adds basic support for git dependencies in a local project.
- Errors if trying to convert to a Lua rockspec.
- `lx add/remove/update` are not implemented yet (see the new issues).
Stacked on #629.
Closes #329.
=> feat: git dependencies for local projects

lux-cli/src/build.rs, lux-lib/src/lockfile/mod.rs
Stacked on #650.
Because we install dependencies before building a local project, they get added to the install tree's lux.toml as entrypoints.
When installing the local project as a rock, we want it to be the only entrypoint.
=> fix(build): dependencies added as install tree entrypoints

lux-cli/src/build.rs, lux-lib/src/lockfile/mod.rs
When running `lx build`, the entry for the built rock in the install tree's lux.lock has all transitive dependencies listed as dependencies.
=> fix(build): transitive dependencies added as dependencies of main rock

lux-cli/src/bin/lx.rs
I think this should get rid of rust messages like
```
thread 'main' panicked at <path>/src/bin/lx.rs:63:75:
called `Result::unwrap()` on an `Err` value: <eyre-error-message>
```
and instead just display the `<eyre-error-message>`.
=> feat(cli): nicer error messages

lux-cli/src/build.rs, lux-cli/src/pin.rs, lux-cli/src/utils/project.rs, lux-lib/src/operations/sync.rs, lux-lib/src/operations/test.rs, lux-lib/src/operations/update.rs
this unifies the API and further prevents mistakes.
one extra issue: we always build a luarocks installation for build dependencies - shouldn't we incorporate this deeper into the API (e.g. as part of `Sync`), instead of hoping that users provide the correct tree? That should be for a different PR, and I make an issue for that if you'd wish :)
=> refactor!: unify `Sync` by making it take in a `Project`

lux-lib/src/project/mod.rs
Given a dependency like this:
```toml
[dependencies.foo]
version = "1.0.0"
pin = true
```
`lx update --toml` would result in something like this, losing all non-`version` fields:
```toml
[dependencies]
foo = "1.1.0"
```
After this change, it updates it correctly, to
```toml
[dependencies.foo]
version = "1.1.0"
pin = true
```
=> fix(cli): fields removed on update

lux-cli/src/build.rs, lux-cli/src/pin.rs, lux-cli/src/utils/project.rs, lux-lib/src/config/mod.rs, lux-lib/src/operations/sync.rs, lux-lib/src/operations/test.rs, lux-lib/src/operations/update.rs, lux-lib/src/project/mod.rs, lux-lib/src/tree/mod.rs
This solves a critical issue in how we handle projects - for some reason, `project.tree()` would return the config's tree instead of the project tree (`.lux/`). This PR adds a regression test that makes use of this fix and is necessary for #666 to be finalized.
=> fix(project): use project tree instead of tree provided in configuration

lux-lib/src/lua_rockspec/mod.rs, lux-lib/src/project/mod.rs
Stacked on #670.
This PR completes lux's support for git dependencies.
Closes #646.
=> feat(cli): `lx update` for git dependencies

lux-lib/src/operations/sync.rs
This one is causing a nix build failure (hence the `fix:` prefix).
=> fix(tests): mark test_sync_remove_rocks as impure

lux-lib/tests/build.rs
For some reason, this one is flaky on Windows. The `test_build_multiple_treesitter_parsers` seems to be doing fine.
=> ci: disable test that is flaky on windows

.github/workflows/continuous-deployment.yml
This should make the build hopefully succeed now and allow us to vendor valid builds for `cargo binstall`. In the near future, I also want to extend this to building lux-lua so that lux.nvim can also pull it down `blink.cmp` style.
=> ci(cd): don't build for windows targets

lux-cli/src/build.rs, lux-cli/src/check.rs, lux-cli/src/install.rs, lux-cli/src/install_rockspec.rs, lux-cli/src/pack.rs, lux-cli/src/uninstall.rs, lux-lib/src/operations/exec.rs, lux-lib/src/operations/install.rs, lux-lib/src/operations/sync.rs, lux-lib/src/operations/test.rs, lux-lib/src/operations/update.rs, lux-lib/tests/install.rs
WIP - similar in vain to the `Sync` refator, aiming to limit mistakes that can be made as a result of mismatched trees.
=> refactor!: unify `Install` tree operations

lux-lib/src/build/mod.rs, lux-lib/src/lua_rockspec/rock_source.rs, lux-lib/src/upload/mod.rs
Back when I implemented this, I wasn't aware that luarocks would error if the source table has any fields it doesn't know about.
=> fix: remove hash field from `RockSourceInternal`

lux-lib/src/lua_installation/mod.rs
Fixes #706 
@kuator when this has been merged/released, you may need to remove the `.lux` directory in your project.
=> fix: error when luajit is not aliased to lua

lux-cli/Cargo.toml, lux-lib/Cargo.toml, nix/overlay.nix
Fixes #725.
We build Lux with luajit and #725 is a luajit limitation.
Solution: Build Lux with Lua 5.4.
@vhyrro fyi, in lux.nvim, we'll have to use lux-lua built against Lua 5.1 (not luajit) if we want to prevent it from running into that issue.
(We should do that anyway, as not all Neovim builds ship with luajit).
I've also enabled the `vendored-lua` feature by default, so that we can build lux and run tests in a devShell with a different lua version.
=> fix: unable to parse large luarocks manifest

lux-cli/src/run_lua.rs, lux-lib/src/build/utils.rs, lux-lib/src/config/mod.rs, lux-lib/src/lua_installation/mod.rs, lux-lib/src/operations/run.rs, lux-lib/src/operations/run_lua.rs, lux-lib/tests/build.rs, lux-lib/tests/exec.rs, lux-lib/tests/install.rs, lux-lib/tests/luarocks_installation.rs, lux-lib/tests/test.rs, lux-lib/tests/tree.rs
Fixes #745.
Our `lua` binary detection currently doesn't take the specified Lua version into account.
=> fix!: more robust lua binary detection

lux-lua/src/project.rs
small usability fix that is going to help improve speeds and prevent unnecessary directory traversals
=> refactor(lux-lua): make `new` match exact project path and add `new_fuzzy`

.gitignore, Cargo.lock, lux-cli/src/install_lua.rs, lux-cli/src/lib.rs, lux-cli/src/pack.rs, lux-lib/Cargo.toml, lux-lib/resources/test/sample-project-busted-nlua/.busted, lux-lib/resources/test/sample-project-busted-nlua/.gitignore, lux-lib/resources/test/sample-project-busted-nlua/lua/foo.lua, lux-lib/resources/test/sample-project-busted-nlua/lux.toml, lux-lib/resources/test/sample-project-busted-nlua/spec/example_spec.lua, lux-lib/src/build/luarocks.rs, lux-lib/src/build/mod.rs, lux-lib/src/build/source.rs, lux-lib/src/build/utils.rs, lux-lib/src/lua_installation/mod.rs, lux-lib/src/lua_rockspec/test_spec.rs, lux-lib/src/luarocks/install_binary_rock.rs, lux-lib/src/operations/fetch.rs, lux-lib/src/operations/pack.rs, lux-lib/src/operations/sync.rs, lux-lib/src/operations/test.rs, lux-lib/tests/exec.rs, lux-lib/tests/luarocks_installation.rs, lux-lib/tests/test.rs
Closes #715.
Supersedes #716.
This implements a `busted-nlua` test backend.
It also adds a fix to prevent race conditions when installing lua sources.
=> feat: busted-nlua test backend

.github/workflows/nix-build.yml
Should save us some time. I don't think we need to be this rigorous about testing on multiple platforms.
=> ci: remove x86_64-darwin builds

lux-lib/src/path.rs
Fixes #526 
Succeeds #790 (I renamed the branch)
You can set `exit` equal to `os.exit` so that you can run `exit()` in a lua repl
=> feat(repl): alias `exit` to `os.exit()`

lux-lib/src/upload/mod.rs
Fixes #794 
Trailing slashes are important when calling `.join` on a URL. Without them, the last component gets replaced.
=> fix(upload): construction of luarocks server URLs

lux-lib/resources/test/sample-project-no-source/lux.toml, lux-lib/src/build/mod.rs, lux-lib/tests/build.rs
=> fix(build)!: `copy_directorys` drops subdirectories

Cargo.lock, lux-cli/Cargo.toml, lux-cli/src/bin/lx.rs, lux-cli/src/completion.rs, lux-cli/src/lib.rs
Hi! 👋 
As an user that installed lux via cargo install, I wanted to have an option to generate autocompletions right from the CLI. That allows me to easily do:
```bash
lx completion zsh > ~/.zsh/completions/_lx
```
```
➜  lux git:(feature/add-shell-completions) ./target/debug/lx completion --help
Generate autocompletion scripts for the shell
Usage: lx completion [SHELL]
Arguments:
[SHELL]  The shell to generate the completion script for [default: bash] [possible values: bash, elvish, fish, powershell, zsh]
Options:
-h, --help  Print help
```
I later noticed that there’s already some related logic in [xtask/src/main.rs](https://github.com/nvim-neorocks/lux/blob/7ca3daec6c5ea237253846abb1f06bbf85f94ceb/xtask/src/main.rs), though it seems intended for a different use case. I’m not sure if or …
=> feat: expose shell completions in main binary

lux-lib/src/package/mod.rs, lux-lib/src/package/version.rs
=> feat!: don't include specrev when substituting `$(VERSION)`

Cargo.lock, lux-cli/src/install_lua.rs, lux-cli/src/install_rockspec.rs, lux-cli/src/pack.rs, lux-lib/Cargo.toml, lux-lib/src/build/mod.rs, lux-lib/src/build/utils.rs, lux-lib/src/lua_installation/mod.rs, lux-lib/src/luarocks/install_binary_rock.rs, lux-lib/src/luarocks/luarocks_installation.rs, lux-lib/src/operations/build_lua.rs, lux-lib/src/operations/build_project.rs, lux-lib/src/operations/install/mod.rs, lux-lib/src/operations/mod.rs, lux-lib/src/project/project_toml.rs, lux-lib/src/rockspec/mod.rs, lux-lib/tests/build.rs, lux-lib/tests/build_lua.rs, lux-lib/tests/luarocks_installation.rs, lux-workspace-hack/Cargo.toml, nix/overlay.nix
Fixes #789.
The `lua-src` and `luajit-src` crates are meant to be used at build time, not runtime.
When using a pre-built lux binary, the respective Lua source directories of these crates don't exist.
So instead of relying on those crates to build Lua, Lux should fetch the sources and then build them.
This has the added benefit that lux now builds a Lua binary, too. So users don't need to have a Lua installation to be able to run commands like `lx lua` or `lx run`. It also opens the door for the possibility of bundling Lua applications.
Note: I am not putting this in a draft state, because I need to run the tests on Windows.
Status:
For now, we hard-code the source URLs, versions and source hashes. We may want to make this configurable at a later time (yagni for now).
=> feat!: manage lua installations internally

.gitignore, Cargo.lock, README.md, lux-cli/Cargo.toml, lux-cli/src/bin/lx.rs, lux-cli/src/check.rs, lux-cli/src/lib.rs, lux-cli/src/lint.rs, lux-cli/src/project/files.rs, lux-cli/src/project/mod.rs, lux-lib/src/operations/gen_luarc.rs, lux-lib/src/project/mod.rs, lux-workspace-hack/Cargo.toml
Stacked on #836.
I think this is pretty much done. But we need to wait for `emmylua_check` to release a version that lets us disable the `cli` feature.
With this, #63 will become more relevant, as it gives lots of `undefined-global` errors in my tests.
=> feat: `lx check` command for luaCATS typechecks

Cargo.lock, Cargo.toml, flake.nix, lux-cli/Cargo.toml, lux-lib/Cargo.toml, lux-lua/Cargo.toml, lux-workspace-hack/Cargo.toml, nix/overlay.nix
- lifts patch version constraints
- updates dependencies in lockfile
- fixes the nix build which broke because of the `vendored` feature (I guess it was fetching cached derivations).
=> chore(deps): update

Cargo.lock, Cargo.toml, lux-cli/Cargo.toml, lux-cli/src/pack.rs, lux-lib/Cargo.toml, lux-lib/src/build/luarocks.rs, lux-lib/src/build/mod.rs, lux-lib/src/build/utils.rs, lux-lib/src/git/utils.rs, lux-lib/src/hash.rs, lux-lib/src/lua_rockspec/rock_source.rs, lux-lib/src/luarocks/install_binary_rock.rs, lux-lib/src/luarocks/luarocks_installation.rs, lux-lib/src/manifest/mod.rs, lux-lib/src/operations/build_lua.rs, lux-lib/src/operations/pack.rs, lux-lib/src/operations/unpack.rs
The `tempdir` crate has been unmaintained for about 7 years.
Fixes https://github.com/lumen-oss/lux/security/dependabot/19
=> refactor(deps): replace unmaintained `tempdir` with `tempfile`
