lumen-oss/lux

- rocks-lib/Cargo.toml
- rocks-lib/src/rockspec/build/builtin.rs
- rocks-lib/src/rockspec/build/cmake.rs
- rocks-lib/src/rockspec/build/make.rs
- rocks-lib/src/rockspec/build/mod.rs
- rocks-lib/src/rockspec/mod.rs
> feat(rockspec): build backend specs

- rocks-lib/Cargo.toml
- rocks-lib/src/rockspec/build/builtin.rs
- rocks-lib/src/rockspec/build/cmake.rs
- rocks-lib/src/rockspec/build/make.rs
- rocks-lib/src/rockspec/build/mod.rs
- rocks-lib/src/rockspec/mod.rs
- rocks-lib/src/rockspec/test_spec.rs
> feat(rockspec): parse test spec

- flake.nix
I haven't figured out how to get the pre-commit hooks/ci lints working yet. Will try that again later.
> chore: add clippy to nix shell

- .gitignore
- rocks-lib/src/rockspec/build/builtin.rs
- rocks-lib/src/rockspec/build/mod.rs
- rocks-lib/src/rockspec/dependency.rs
- rocks-lib/src/rockspec/mod.rs
- rocks-lib/src/rockspec/platform.rs
- rocks-lib/src/rockspec/rock_source.rs
- rocks-lib/src/rockspec/test_spec.rs
> feat(rockspec): per platform overrides

- rocks-lib/src/rockspec/platform.rs
It really shouldn't have an `Ord` instance.
I'm not sure about how we sort platforms by specificity (see the comment I added).
> fix(platform): remove `Ord` instance of `PlatformIdentifier`

- rocks-bin/src/debug.rs
- rocks-bin/src/list.rs
- rocks-bin/src/main.rs
- rocks-bin/src/update.rs
- rocks-lib/src/config/mod.rs
stacked on #31
This PR aims to refactor the CLI to be generally easier to use. Note: this is a breaking change and breaks compatibility with luarocks itself.
> feat!: make CLI more ergonomic

- rocks-lib/src/build/mod.rs
- rocks-lib/src/rockspec/dependency.rs
stacked on #33 
This PR automatically infers the required Lua version based on the target rockspec's dependency information (e.g. `lua ~> 5.1` will automatically switch `rocks` to 5.1 mode). `rocks` will always try to use the latest possible Lua release given a constraint.
Soon, I'd like to add a third fallback in the form of a global configuration option which defines the preferred lua version.
Also fixed a bug in dependency parsing where `lua>=5.1` (without spaces) wouldn't be correctly parsed and added the appropriate regression cases.
> fix: automatically infer lua version when building

- .github/workflows/nix-build.yml
- flake.lock
- flake.nix
This brings our build infrastructure up to date.
> build(nix): infrastructure maintenance

- .cargo/config.toml
- CONTRIBUTING.md
- rocks-lib/Cargo.toml
- rocks-lib/src/build/builtin.rs
- rocks-lib/src/tree/mod.rs
- rocks-lib/src/tree/snapshots/rocks_lib__tree__tests__tree_list.snap.new
> tests: `test_nosandbox` feature for running tests locally

- Cargo.lock
- rocks-bin/Cargo.toml
- rocks-bin/src/project/write_new.rs
- rocks-bin/src/utils/github_metadata.rs
- rocks-lib/Cargo.toml
Stacked on #55 
See: https://github.com/nvim-neorocks/rocks/security/dependabot
> chore(deps): apply dependabot security recommendations

- CONTRIBUTING.md
- README.md
- flake.nix
- rocks-bin/src/project/write_new.rs
- rocks-lib/Cargo.toml
- rocks-lib/src/lua_package/mod.rs
- rocks-lib/src/lua_package/version.rs
Re-opening because #56 was accidentally closed.
> docs: contributing guide

- rocks-bin/src/main.rs
- rocks-bin/src/outdated.rs
- rocks-lib/src/config/mod.rs
- rocks-lib/src/luarock/mod.rs
- rocks-lib/src/luarock/outdated.rs
- rocks-lib/src/tree/list.rs
This command will display outdated rocks in a nice tree-view.
> feat: `rocks outdated` command

- Cargo.lock
- rocks-bin/src/install_lua.rs
- rocks-bin/src/main.rs
- rocks-bin/src/outdated.rs
- rocks-lib/Cargo.toml
- rocks-lib/src/build/builtin.rs
- rocks-lib/src/build/mod.rs
- rocks-lib/src/config/mod.rs
- rocks-lib/src/lib.rs
- rocks-lib/src/lua/mod.rs
- rocks-lib/src/lua_installation/mod.rs
- rocks-lib/src/lua_package/mod.rs
- rocks-lib/src/lua_package/outdated.rs
- rocks-lib/src/rockspec/build/mod.rs
- rocks-lib/src/rockspec/build/utils/mod.rs
- rocks-lib/src/tree/list.rs
- rocks-lib/src/tree/snapshots/rocks_lib__tree__tests__tree_list.snap.new
> feat: `rocks install-lua` / Lua compilation

- rocks-lib/src/lua_package/outdated.rs
stacked on #69 (nice)
Just a simple test to ensure that `has_update()` works as intended :)
> test: add test for `rock.has_update()`

- Cargo.lock
- rocks-bin/Cargo.toml
- rocks-bin/src/format.rs
- rocks-bin/src/main.rs
- rocks-lib/src/config/mod.rs
- rocks-lib/src/lua_package/outdated.rs
- rocks-lib/src/project/mod.rs
Surprise PR! This is a new command that invokes `stylua` for every Lua file in the codebase.
Things to do:
Future things:
> feat: `rocks fmt` command

- Cargo.lock
- rocks-bin/src/build.rs
- rocks-bin/src/list.rs
- rocks-bin/src/main.rs
- rocks-bin/src/outdated.rs
- rocks-lib/Cargo.toml
- rocks-lib/src/build/builtin.rs
- rocks-lib/src/build/mod.rs
- rocks-lib/src/operations/install.rs
- rocks-lib/src/tree/list.rs
- rocks-lib/src/tree/mod.rs
This PR automatically installs the dependencies of a given project.
TODOs:
> feat: automatic dependency installation

- rocks-lib/resources/test/lua-cjson-2.1.0-1.rockspec
- rocks-lib/src/rockspec/build/builtin.rs
- rocks-lib/src/rockspec/build/mod.rs
- rocks-lib/src/rockspec/dependency.rs
- rocks-lib/src/rockspec/mod.rs
- rocks-lib/src/rockspec/platform.rs
- rocks-lib/src/rockspec/rock_source.rs
- rocks-lib/src/rockspec/test_spec.rs
> fix: per platform overrides do not merge properly

- rocks-bin/src/main.rs
- rocks-bin/src/purge.rs
- rocks-bin/src/remove.rs
- rocks-lib/src/lua_package/mod.rs
- rocks-lib/src/lua_package/version.rs
- rocks-lib/src/operations/mod.rs
- rocks-lib/src/operations/remove.rs
- rocks-lib/src/tree/mod.rs
This PR adds basic support for `rocks purge` and `rocks remove`.
There are no tests for this yet, I'll get those set up tomorrow.
> feat: implement `rocks purge` and `rocks remove`

- Cargo.lock
- rocks-bin/Cargo.toml
- rocks-bin/src/build.rs
- rocks-bin/src/download.rs
- rocks-bin/src/install.rs
- rocks-bin/src/install_lua.rs
- rocks-bin/src/main.rs
- rocks-bin/src/purge.rs
- rocks-bin/src/remove.rs
- rocks-bin/src/unpack.rs
- rocks-lib/Cargo.toml
- rocks-lib/src/build/fetch.rs
- rocks-lib/src/build/mod.rs
- rocks-lib/src/lib.rs
- rocks-lib/src/lua_package/mod.rs
- rocks-lib/src/lua_package/outdated.rs
- rocks-lib/src/operations/download.rs
- rocks-lib/src/operations/install.rs
- rocks-lib/src/operations/remove.rs
- rocks-lib/src/operations/unpack.rs
- rocks-lib/src/progress.rs
- rocks-lib/tests/build.rs
Closes #66.
Here's an example of the output:
> feat: progress spinners

- .editorconfig
- rocks-lib/resources/test/make-project/Makefile
- rocks-lib/resources/test/make-project/make-project-scm-1.rockspec
- rocks-lib/src/build/builtin.rs
- rocks-lib/src/build/fetch.rs
- rocks-lib/src/build/make.rs
- rocks-lib/src/build/mod.rs
- rocks-lib/src/build/variables.rs
- rocks-lib/src/config/mod.rs
- rocks-lib/src/lua_installation/mod.rs
- rocks-lib/src/rockspec/build/mod.rs
- rocks-lib/src/rockspec/rock_source.rs
- rocks-lib/src/tree/mod.rs
- rocks-lib/tests/build.rs
This PR adds the `make` build type in rockspecs.
This is a draft as I haven't tested it whatsoever on real world rocks :)
> feat: `make` build type

- rocks-lib/src/build/builtin.rs
- rocks-lib/src/build/make.rs
- rocks-lib/src/build/mod.rs
- rocks-lib/src/rockspec/build/mod.rs
- rocks-lib/src/rockspec/build/utils/mod.rs
- rocks-lib/tests/build.rs
> fix: don't change working directory

- Cargo.lock
- rocks-lib/Cargo.toml
- rocks-lib/src/rockspec/build/builtin.rs
- rocks-lib/src/rockspec/build/mod.rs
- rocks-lib/src/rockspec/mod.rs
- rocks-lib/src/rockspec/platform.rs
- rocks-lib/src/rockspec/serde_util.rs
> fix(rockspec): support empty tables and unknown platforms

- rocks-lib/src/operations/fetch.rs
This increases our compatibility with other rocks by properly extracting data from `.tar.gz` files :)
> fix: unpack `.tar.gz` files recursively if there is one directory

- Cargo.lock
- flake.nix
- nix/overlay.nix
- rocks-bin/src/main.rs
- rocks-bin/src/upload.rs
- rocks-lib/Cargo.toml
- rocks-lib/src/lib.rs
- rocks-lib/src/upload/mod.rs
> feat: `rocks upload`

- rocks-lib/src/config/mod.rs
> cleanup: remove todo comment

- README.md
- rocks-bin/src/main.rs
> docs(readme): comparison with luarocks

- rocks-lib/resources/test/sample-tree/5.1/lock.json
- rocks-lib/src/lockfile/mod.rs
> feat(lockfile): save as pretty-formatted json

- rocks-lib/src/tree/mod.rs
> tests: don't modify lockfile in sample tree

- Cargo.lock
- README.md
- flake.nix
- rocks-lib/Cargo.toml
- rocks-lib/src/build/utils.rs
- rocks-lib/src/lua_installation/mod.rs
This should hopefully be more robust.
> feat: use pkg-config to detect system lua installation

- rocks-lib/src/build/mod.rs
> feat: source integrity checks

- .cargo/config.toml
- Cargo.lock
- Cargo.toml
- nix/overlay.nix
- rocks-bin/src/lib.rs
- xtask/Cargo.toml
- xtask/src/main.rs
> feat: man pages and shell completions

- flake.nix
> chore(nix/devShell): add ra-multiplex

- rocks-bin/src/check.rs
- rocks-lib/src/operations/run.rs
- rocks-lib/src/operations/test.rs
- rocks-lib/src/operations/update.rs
> refactor(test): move custom builder syntax to `bon`

- Cargo.lock
- rocks-bin/src/check.rs
- rocks-lib/Cargo.toml
- rocks-lib/src/build/mod.rs
- rocks-lib/src/operations/run.rs
- rocks-lib/src/operations/test.rs
- rocks-lib/src/operations/update.rs
Supercedes #312 with a much better (compile-time checked) implementation :)
> refactor(build): move custom builder syntax to `bon`

- rocks-lib/src/build/mod.rs
> feat(install): auto-install `doc` directories

- rocks-lib/src/build/mod.rs
- rocks-lib/src/tree/mod.rs
This can be useful for getting info about a package.
> feat(build): install rockspec

- Cargo.lock
- rocks-lib/Cargo.toml
- rocks-lib/resources/test/patch_test/pack.lua
- rocks-lib/src/build/mod.rs
- rocks-lib/src/build/patch.rs
- rocks-lib/src/rockspec/build/mod.rs
> feat(build): apply rockspec patches

- rocks-lib/src/rockspec/platform.rs
This pull request includes changes to the `PlatformSupport` code - the changes improve the platform parsing logic by distinguishing between exclusive and inclusive platform matches. These were improperly handled earlier but still somehow passed our tests (maybe because we never directly compared the structs themselves to my knowledge? idk)
Improvements to platform parsing logic:
* Modified the condition to check for any negative matches instead of all negative matches to determine if platforms should be matched exclusively.
* Simplified the inclusive matching branch to only validate positive matches.
> fix: proper parsing of `PlatformSupport`

- Cargo.lock
- rocks-bin/src/add.rs
- rocks-bin/src/build.rs
- rocks-bin/src/install.rs
- rocks-bin/src/lib.rs
- rocks-bin/src/main.rs
- rocks-bin/src/project/new.rs
- rocks-bin/src/utils/install.rs
- rocks-bin/src/utils/mod.rs
- rocks-lib/Cargo.toml
- rocks-lib/src/lockfile/mod.rs
- rocks-lib/src/luarocks/luarocks_installation.rs
- rocks-lib/src/manifest/mod.rs
- rocks-lib/src/operations/install.rs
- rocks-lib/src/operations/resolve.rs
- rocks-lib/src/package/mod.rs
- rocks-lib/src/package/outdated.rs
- rocks-lib/src/package/version.rs
- rocks-lib/src/project/mod.rs
- rocks-lib/src/project/rocks_toml.rs
- rocks-lib/src/remote_package_db/mod.rs
- rocks-lib/src/rockspec/mod.rs
- rocks-lib/src/tree/mod.rs
- rocks-lib/tests/build.rs
Summary: rocks add and refactors existing code to enforce the handling of unsupplied package version requirements.
> feat: `rocks add`

- rocks-lib/src/package/version.rs
> feat: correct invalid semver versions

- rocks-bin/src/path.rs
- rocks-bin/src/run.rs
- rocks-bin/src/run_lua.rs
- rocks-lib/src/luarocks/luarocks_installation.rs
- rocks-lib/src/operations/install.rs
- rocks-lib/src/operations/run.rs
- rocks-lib/src/operations/test.rs
- rocks-lib/src/path.rs
> fix: make `rocks lua` also provide project paths

- Cargo.lock
- nix/overlay.nix
- rocks-lib/Cargo.toml
- rocks-lib/resources/test/sample-tree/5.1/lock.json
- rocks-lib/src/hash.rs
- rocks-lib/src/lockfile/mod.rs
- rocks-lib/src/lockfile/snapshots/rocks_lib__lockfile__tests__add_rocks.snap
- rocks-lib/src/lockfile/snapshots/rocks_lib__lockfile__tests__parse_lockfile.snap
- rocks-lib/src/luarocks/install_binary_rock.rs
- rocks-lib/src/operations/pack.rs
Supercedes #400, which was closed because of a `jj abandon` of the PR it was stacked on.
Stacked on #385.
> fix(hash): ensure path hashing compatibility with nix-hash

- rocks-bin/src/add.rs
- rocks-bin/src/build.rs
- rocks-bin/src/sync.rs
- rocks-bin/src/test.rs
- rocks-lib/resources/test/rocks.lock
- rocks-lib/resources/test/sample-project-busted/.gitignore
- rocks-lib/src/lockfile/mod.rs
- rocks-lib/src/luarocks/luarocks_installation.rs
- rocks-lib/src/operations/install.rs
- rocks-lib/src/operations/sync.rs
- rocks-lib/src/operations/test.rs
- rocks-lib/src/project/mod.rs
- rocks-lib/src/remote_package_db/mod.rs
- rocks-lib/tests/test.rs
> feat!: add build/test dependencies to rocks.lock

- rocks-bin/src/add.rs
- rocks-bin/src/build.rs
- rocks-bin/src/sync.rs
- rocks-bin/src/test.rs
- rocks-lib/resources/test/rocks.lock
- rocks-lib/resources/test/sample-project-busted/.gitignore
- rocks-lib/src/lockfile/mod.rs
- rocks-lib/src/luarocks/luarocks_installation.rs
- rocks-lib/src/operations/install.rs
- rocks-lib/src/operations/sync.rs
- rocks-lib/src/operations/test.rs
- rocks-lib/src/project/mod.rs
- rocks-lib/src/remote_package_db/mod.rs
- rocks-lib/tests/test.rs
This is in preparation for #395.
> refactor(lockfile): extract `LocalPackageLock` type

- rocks-lib/resources/test/rocks.lock
- rocks-lib/resources/test/sample-tree/5.1/lock.json
- rocks-lib/src/build/mod.rs
- rocks-lib/src/lockfile/mod.rs
- rocks-lib/src/lockfile/snapshots/rocks_lib__lockfile__tests__add_rocks.snap
- rocks-lib/src/lockfile/snapshots/rocks_lib__lockfile__tests__parse_lockfile.snap
- rocks-lib/src/luarocks/install_binary_rock.rs
- rocks-lib/src/tree/mod.rs
- rocks-lib/src/tree/snapshots/rocks_lib__tree__tests__tree_list.snap
> feat(lockfile): add source_url info

- lux-lib/src/config/mod.rs
- lux-lib/src/luarocks/luarocks_installation.rs
- lux-lib/src/project/mod.rs
> feat: allow `--tree` to override project tree

- lux-cli/src/update.rs
- lux-lib/src/operations/update.rs
> feat(update): take an optional list of packages

- lux-cli/src/update.rs
- lux-lib/src/operations/update.rs
- lux-lib/src/project/mod.rs
> feat(update): `--toml` flag to upgrade packages in lux.toml

- .gitignore
- lux-cli/src/format.rs
- lux-cli/src/project/debug.rs
- lux-lib/src/project/project_toml.rs
Fixes ~~two~~ three small issues I encountered when going through the tutorial.
> Simple fixes

- lux-cli/src/run_lua.rs
> feat: build project on `lx lua`

- Cargo.lock
- lux-lib/Cargo.toml
- lux-lib/src/build/utils.rs
- lux-lib/src/operations/fetch.rs
> feat(build): respect ignore files when copying source

- lux-lib/src/project/project_toml.rs
This doesn't seem to cause any chaos in other parts of the application. Besides, nobody should rely on the fact that `lua` is a dependency, because it fundamentally isn't a dependency.
> fix: do not include `lua` as part of dependencies in TOML rockspecs

- .github/workflows/release-please.yml
Now's as good of a time as ever to start versioning our code (obviously still in the semver zero range)
> ci: add `release-please` workflow

- lux-lib/src/upload/mod.rs
This fixes `lx upload` failing in all cases (how was this not caught earlier? at least one test should have caught this)
> fix(upload): fix upload searching for old `project.rockspec` file

- README.md
this follows the template
(let me know what you think)
> docs(readme): play around with logo structure

- lux-lib/resources/test/ltui-2.8-2.rockspec
- lux-lib/resources/test/luasystem-0.4.4-1.rockspec
- lux-lib/src/lua_rockspec/build/builtin.rs
- lux-lib/src/lua_rockspec/mod.rs
- lux-lib/src/lua_rockspec/serde_util.rs
> fix(rockspec): support undocumented string/array duality

- Cargo.lock
- lux-cli/Cargo.toml
- lux-cli/src/run_lua.rs
- lux-lib/resources/test/lux.lock
- lux-lib/resources/test/sample-tree/5.1/lux.lock
- lux-lib/src/lockfile/mod.rs
- lux-lib/src/lockfile/snapshots/lux_lib__lockfile__tests__add_rocks.snap
- lux-lib/src/lockfile/snapshots/lux_lib__lockfile__tests__parse_lockfile.snap
- lux-lib/src/package/mod.rs
- lux-lib/src/package/version.rs
- lux-lib/src/project/project_toml.rs
- lux-lib/src/tree/snapshots/lux_lib__tree__tests__tree_list.snap
- lux-lib/src/which/mod.rs
This is a breaking change because it changes the hashes in the lockfile.
Note: releaze-plz won't detect these kinds of breaking changes.
Fixes #544
> fix!: incompatible generated rockspec dependencies

- lux-lib/src/lua_rockspec/build/mod.rs
- lux-lib/src/lua_rockspec/mod.rs
- lux-lib/src/lua_rockspec/serde_util.rs
- lux-lib/src/project/project_toml.rs
> fix: unsupported off-spec `install.bin` array field

- CHANGELOG.md
It's kind of the opposite of keepachangelog :sweat_smile:
> docs(changelog): remove keepachangelog note

- lux-lib/src/upload/mod.rs
> feat(upload): refuse to upload indeterministic rockspecs

- lux-lib/src/build/utils.rs
- lux-lib/src/lua_installation/mod.rs
- lux-lib/src/luarocks/luarocks_installation.rs
- lux-lib/src/operations/sync.rs
>  fix: install pre-packaged luarocks on windows

- Cargo.lock
- lux-lib/Cargo.toml
- lux-lib/src/build/cmake.rs
- lux-lib/src/build/command.rs
- lux-lib/src/build/make.rs
- lux-lib/src/build/utils.rs
- lux-lib/src/build/variables.rs
- lux-lib/src/config/mod.rs
- lux-lib/src/lua_installation/mod.rs
- lux-lib/src/package/version.rs
- lux-lib/src/tree/mod.rs
Adds support for recursive and flat variables.
> feat: better variable expansion + error on missing variables

- Cargo.toml
Closes #531
>[!IMPORTANT]
>
>This PR has two commits and should be rebase-merged.
> perf: enable LTO + set `codegen-units = 1` in release profile

- lux-lib/src/manifest/mod.rs
> fix(manifest): re-download if corrupted

- Cargo.lock
- lux-cli/src/build.rs
- lux-cli/src/check.rs
- lux-cli/src/install_rockspec.rs
- lux-cli/src/pack.rs
- lux-cli/src/uninstall.rs
- lux-cli/src/utils/install.rs
- lux-lib/src/build/builtin.rs
- lux-lib/src/build/mod.rs
- lux-lib/src/build/source.rs
- lux-lib/src/build/utils.rs
- lux-lib/src/lua_rockspec/build/mod.rs
- lux-lib/src/lua_rockspec/mod.rs
- lux-lib/src/lua_rockspec/rock_source.rs
- lux-lib/src/luarocks/luarocks_installation.rs
- lux-lib/src/operations/download.rs
- lux-lib/src/operations/exec.rs
- lux-lib/src/operations/install_spec.rs
- lux-lib/src/operations/resolve.rs
- lux-lib/src/operations/sync.rs
- lux-lib/src/operations/test.rs
- lux-lib/src/operations/update.rs
- lux-lib/src/package/mod.rs
- lux-lib/src/package/version.rs
- lux-lib/tests/install.rs
- lux-workspace-hack/Cargo.toml
Stacked on #623.
A preparation for #329.
> feat(lib/install): support installing from alternate sources

- Cargo.lock
- flake.nix
- lux-lib/Cargo.toml
- lux-lib/src/config/mod.rs
- lux-lib/src/config/tree.rs
- lux-lib/src/lib.rs
- lux-lib/src/lua.rs
- lux-lib/src/lua_rockspec/dependency.rs
- lux-lib/src/lua_rockspec/partial.rs
- lux-lib/src/package/mod.rs
- lux-lib/src/project/mod.rs
- lux-lib/src/remote_package_db/mod.rs
- lux-lib/src/rockspec/lua_dependency.rs
- lux-lua/Cargo.toml
- lux-lua/src/config.rs
- lux-lua/src/lib.rs
- lux-lua/src/project.rs
- lux-workspace-hack/Cargo.toml
- nix/overlay.nix
This PR will be a large one. I'm hoping to increase the reach of the Lua API and get it properly tested in preparation for rocks.nvim 3.0 and other integrations.
> feat: more Lua coverage + Lua tests

- lux-cli/src/project/new.rs
Closes #682
Basically just automatically add a `.gitignore` file containing `.lux/` to the project root
> feat: Autogenerate a .gitignore file

- lux-lib/src/manifest/mod.rs
- lux-lib/src/operations/download.rs
This ought to help troubleshoot what is actually going on in #700, before we implement a plaintext mainfest fallback as a workaround.
> feat: more detailed zip error messages

- lux-cli/src/doc.rs
- lux-cli/src/exec.rs
- lux-cli/src/install.rs
- lux-cli/src/list.rs
- lux-cli/src/outdated.rs
- lux-cli/src/pack.rs
- lux-cli/src/pin.rs
- lux-cli/src/purge.rs
- lux-cli/src/run_lua.rs
- lux-cli/src/uninstall.rs
- lux-cli/src/utils/project.rs
- lux-lib/src/config/mod.rs
- lux-lib/src/lua_installation/mod.rs
- lux-lib/src/luarocks/install_binary_rock.rs
- lux-lib/src/manifest/mod.rs
- lux-lib/src/operations/exec.rs
- lux-lib/src/operations/remove.rs
- lux-lib/src/operations/run_lua.rs
- lux-lib/src/operations/update.rs
- lux-lib/src/project/project_toml.rs
- lux-lib/src/rockspec/mod.rs
- lux-lib/src/which/mod.rs
- lux-lib/tests/build.rs
- lux-lib/tests/exec.rs
- lux-lib/tests/install.rs
- lux-lib/tests/luarocks_installation.rs
- lux-lib/tests/test.rs
- lux-lib/tests/tree.rs
> fix!: luajit version autodetection + prevent manifest download if lua version not detected

- Cargo.lock
- lux-cli/Cargo.toml
- lux-lib/Cargo.toml
- lux-lua/Cargo.toml
- xtask-lua/Cargo.toml
Just some dependency maintenance...
> chore(deps): upgrade

- lux-lib/src/build/mod.rs
- lux-lib/src/tree/mod.rs
> fix!: bin scripts installed into tree's root

- lux-lib/src/luarocks/luarocks_installation.rs
- lux-lib/src/manifest/mod.rs
- lux-lib/src/operations/download.rs
- lux-lib/src/operations/fetch.rs
> fix: add checks to prevent trying to unpack HTML response

- lux-cli/src/project/new.rs
- lux-lib/src/tree/mod.rs
> feat: add .gitignore to install tree root

- lux-lib/resources/test/sample-project-no-build-spec/src/bin/hello
- lux-lib/src/build/utils.rs
> fix!: always wrap lua bin scripts

- lux-cli/src/bin/lx.rs
- lux-cli/src/lib.rs
- lux-lib/src/config/mod.rs
> feat(cli): flag to override variables

- lux-cli/src/bin/lx.rs
- lux-cli/src/lib.rs
- lux-lib/src/build/mod.rs
- lux-lib/src/build/utils.rs
- lux-lib/src/config/mod.rs
- lux-lib/src/tree/mod.rs
... for example if called with `lx -v LUA=nlua`
Stacked on #765
> fix(build): lua binaries not wrapped properly

- lux-lib/src/lua_rockspec/rock_source.rs
> feat(rockspec): support `gitrec+` prefixes

- lux-lib/src/upload/mod.rs
Stacked on #797.
I noticed we could potentially leak API keys in error messages.
This ought to prevent that.
Luckily, we haven't encountered this problem, because of #797 :sweat_smile:
> fix(upload): don't leak API key in error messages

- lux-lib/src/build/backend.rs
- lux-lib/src/build/builtin.rs
- lux-lib/src/build/cmake.rs
- lux-lib/src/build/command.rs
- lux-lib/src/build/luarocks.rs
- lux-lib/src/build/make.rs
- lux-lib/src/build/mod.rs
- lux-lib/src/build/rust_mlua.rs
- lux-lib/src/build/source.rs
- lux-lib/src/build/treesitter_parser.rs
> refactor(build)!: use Builder pattern for `BuildBackend` trait

- lux-lib/src/build/backend.rs
- lux-lib/src/build/mod.rs
> refactor(build)!: don't expose `BuildBackend` trait

- lux-cli/src/bin/lx.rs
- lux-cli/src/format.rs
- lux-cli/src/lib.rs
> feat(cli): allow passing path to `fmt`

- lux-lib/resources/test/sample-project-no-source/lux.toml
- lux-lib/src/build/mod.rs
- lux-lib/tests/build.rs
> fix(build): install conf files to etc/conf

- lux-cli/src/bin/lx.rs
- lux-cli/src/completion.rs
- lux-cli/src/lib.rs
> chore(cli/completion): auto-detect shell

- lux-lib/src/build/mod.rs
- lux-lib/src/lockfile/mod.rs
- lux-lib/src/lua_rockspec/rock_source.rs
- lux-lib/src/operations/fetch.rs
- lux-lib/src/project/gen.rs
> fix(build): relax `source.dir` inferring logic

- lux-lib/src/build/utils.rs
We should try to use the external Lua binary if present, to check if a Lua script is compatible.
With the bundled Lua interpreter, we can't load scripts that have incompatible Lua contructs, e.g. from Lua 5.4
> fix(build): lua script detection for all lua versions

- lux-lib/src/project/gen.rs
- lux-lib/src/project/project_toml.rs
> fix: search upwards when substituting `$(REF)`

- lux-lib/resources/test/sample-projects/command-build/.gitignore
- lux-lib/resources/test/sample-projects/command-build/lux.toml
- lux-lib/src/build/command.rs
- lux-lib/src/build/utils.rs
- lux-lib/src/variables.rs
- lux-lib/tests/build.rs
> fix(build): support multiline scripts in `command` backend

- lux-lib/src/lockfile/mod.rs
> feat(lockfile): diff-friendly entrypoints

- lux-lib/src/build/builtin.rs
- lux-lib/src/operations/build_project.rs
> fix(build/builtin): `bin` script installation

- .github/workflows/nix-build.yml
- nix/overlay.nix
- xtask-lua/src/lib.rs
It still fails with `Permission denied` on Darwin. I'll have to look into that another time.
> build(nix): fix lux-lua build on linux

- lux-cli/src/run.rs
- lux-lib/src/operations/run.rs
> feat(cli/run): allow setting the directory with `--dir`

- lux-cli/src/generate_rockspec.rs
- lux-cli/src/install_rockspec.rs
- lux-lib/src/operations/resolve.rs
- lux-lib/src/project/project_toml.rs
> feat: improvements related to our native build backends.

- lux-lib/src/build/mod.rs
- lux-lib/src/build/rust_mlua.rs
- lux-lib/src/build/treesitter_parser.rs
- lux-lib/src/lua_rockspec/build/mod.rs
- lux-lib/src/lua_rockspec/build/rust_mlua.rs
Depends on https://github.com/mlua-rs/luarocks-build-rust-mlua/pull/21 being merged and released.
> build(rust-mlua): support luarocks build backend v0.2.5

- .gitignore
- lux.toml
Depends on:
- #1009 
- https://github.com/mlua-rs/luarocks-build-rust-mlua/pull/21
> build: lux project for lux-lua

- lux-lib/src/git/utils.rs
- lux-lib/src/project/mod.rs
> fix(git-dependencies): handle git tags with specrevs
